"""Add dept_code and project_code columns

Revision ID: 42581f679f59
Revises: 
Create Date: 2025-11-10 13:11:42.666598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42581f679f59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_code', sa.String(length=4), nullable=False))
        batch_op.create_unique_constraint(None, ['dept_code'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_code', sa.String(length=5), nullable=False))
        batch_op.create_unique_constraint(None, ['project_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('project_code')

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('dept_code')

    # ### end Alembic commands ###
